### ISSUE TITLE
Given psi, compute det(J), inv(J) in element midpoints

### ISSUE THREAD

**Issue by fredrikhellman** [gridlod-community/gridlod-on-perturbations#1]
Given psi as a function psi = (psi_1, psi_2, ..., psi_d), where each psi_i is a Q1-function on the fine mesh, we want to compute det(J(x_mid)), inv(J(x_mid)) where x_mid are element midpoints and J = dpsi/dx.

**Comment by TiKeil** [comment]
My idea is to maybe add a file 'perturbation_functions.py' that has multiple psis. Those psis should be classes with functions that are able to compute everything we need. Most of the time we intend to give an explicit form of J, right? 
What do you think?

**Comment by TiKeil** [comment]
This https://github.com/gridlod-community/gridlod-on-perturbations/commit/342bed09649414161ed5e506d3136c162ba9abd0 is what I mean by the previous suggestion

**Comment by fredrikhellman** [comment]
That looks good to me!

One comment: We can either have: (1) y = x + psi(x) or (2) y = psi(x). In the integrals after change of variables, J is really the Jacobian of psi in (2). I think I would prefer to use version (2) as the definition of psi, but it seems like you are using version (1) in plateau_1d. Regarding implementation, it might not matter, or even be preferable to use (1), I don't know. But for the paper, I think we should have a symbol for the full transformation function.

**Comment by TiKeil** [comment]
I am using (1) just for the sake of explanation in the comment line of plateau_1d. But you are right I should change this.

**Comment by fredrikhellman** [comment]
1. I saw that you use solveCoarse in the plateau_2d code. I can't see a reason not to only use solveFine in these initial tests. Just an observation of something that I thought looked odd to me... I might be wrong.
1. We should make it possible to compute psi with a batch of points in one call by passing a vector x of shape [nPoints, d] and get a vector of the same shape back. For J and invJ, we'd get [nPoints, d, d] back. Both numpy det and inv support batch computations already. Batch computations will perform better for many points. Also, we get rid of the loops in the caller.
1. I think we should use a linear addressing of points and elements in the grid. For example, with the change in the previous item, it is not necessary to shape jAj_reshape as [fine, fine] as below
    ```
    jAj_reshape = np.tile(np.eye(2), [fine,fine,1,1])
    ```
    since we can then instead pass all element midpoints to psi.detJ, psi.invJ, psi.evaluate etc., e.g.
    ```
    psi.detJ(tFine)
    ```
    This is a bit of the philosophy behind gridlod: We always have an ordering of all elements and points. This also holds for the perturbed midpoints, since they are logically in a grid layout.

These are things I have thought about, but I really have too little time to fix stuff. So, I would eventually want to do these changes, but if you think they'd be useful you could start on your own. I don't expect you to do that, I just want to share these ideas while I can't find time to work on them on my own.

My experience is that if we fix items 2-3 above, the quite error-prone code on lines 59-62, 70-78, 83-86 and 120-123 (commit 186ee66) in plateau_2d_on_one_axis.py will become much easier to read and (possibly) debug.

**Comment by TiKeil** [comment]
Thanks for the very good comments. I will keep you updated with my progress. 

item 1 has been done in https://github.com/gridlod-community/gridlod-on-perturbations/commit/dbbad48768f34ad97a58d477c74383eb250d4b00

**Comment by TiKeil** [comment]
Currently working on 2) and 3). smooth_1d already has these changed (thought it might be simpler to start with 1d here). see commit https://github.com/gridlod-community/gridlod-on-perturbations/commit/6e824865c0cb977c79d15818a3035c32dd2b9251

**Comment by TiKeil** [comment]
Update @fredrikhellman : 

2) and 3) are now ready for plateau_2d_on_one_axis. See commit https://github.com/gridlod-community/gridlod-on-perturbations/commit/324a3c416cb845b737af198c3e37424cdc4dbcb2
I put the boring stuff to the psi_function and kept it very intuitive in plateau_2d_on_one_axis. Furthermore, I completely avoided to reshape things. This is looking a lot better now. Still there is something wrong on the left side of the solution. 
This maybe also has to do with issue #2 . I will stop here and wait for your comments.

**Comment by fredrikhellman** [comment]
I have reworked this quite a bit. Made performance improvements and some restructuring to reduce code duplication. See branch work_on_mappings, in particular commit c82ebde8f.

**Comment by fredrikhellman** [comment]
We have an interface for psi-functions now. One can either define all functions manually (as in psi_functions.py) or use a CQ1-function and the class in discrete_mapping.py. I think we are done with this issue at this point.
